export const MARKET_INSIGHTS = [
  {
    id: 1,
    slug: 'stearic-acid-market-2025',
    title: 'Stearic Acid Market 2025: Supplier & Distributor Strategies',
    type: 'Supply Chain',
    image: 'https://cdn.chemtradeasia.com/images/blog/1750056330.webp',
    date: '2025-06-16',
    excerpt: 'An in-depth analysis of emerging trends in the global chemical market, focusing on sustainability and digital transformation.',
    isTop: true,
    isFeatured: true,
    author: 'Tradeasia Research',
    readingTime: '8 min read',
    tags: ['Stearic Acid', 'Sustainability', 'Supply Chain Strategy'],
    clickCount: 1560
  },
  {
    id: 2,
    slug: 'crude-glycerine-market-analysis',
    title: 'Crude Glycerine Market Analysis 2021–2033',
    type: 'Pricing Indices',
    image: 'https://cdn.chemtradeasia.com/images/market-insight/supply-chain.webp',
    date: '2025-08-04',
    excerpt: 'Current logistics bottlenecks and their impact on soda ash distribution across Asia-Pacific regions.',
    isTop: false,
    isFeatured: true,
    author: 'Tradeasia Research',
    readingTime: '5 min read',
    tags: ['Crude Glycerine', 'Pricing', 'Market Trends'],
    clickCount: 2450
  },
  {
    id: 3,
    slug: 'high-spec-cetyl-alcohol',
    title: 'High-Spec Cetyl Alcohol for Enhanced Downstream Efficiency',
    type: 'Applications and Buyers',
    image: 'https://cdn.chemtradeasia.com/images/market-insight/regulatory.webp',
    date: '2026-01-19',
    excerpt: 'Key changes in chemical regulations for the European Economic Area that every exporter must know.',
    isTop: false,
    isFeatured: true,
    author: 'Tradeasia Research',
    readingTime: '10 min read',
    tags: ['Cetyl Alcohol', 'Manufacturing', 'Yield Optimization'],
    clickCount: 1890
  },
  {
    id: 4,
    slug: 'chain-length-integrity',
    title: 'Chain-Length Integrity: The Invisible Driver of Manufacturing Yield in 2026',
    type: 'Regulatory and Compliance',
    image: 'https://cdn.chemtradeasia.com/images/market-insight/pricing.webp',
    date: '2026-02-02',
    excerpt: 'Tracking price fluctuations and market demand for caustic soda in the first quarter of 2024.',
    isTop: false,
    isFeatured: true,
    author: 'Tradeasia Research',
    readingTime: '6 min read',
    tags: ['Manufacturing Yield', 'Production efficiency', 'Chain Length'],
    clickCount: 3200
  },
  {
    id: 5,
    slug: 'the-green-chemistry-pivot',
    title: 'The Green Chemistry Pivot: How B2B Palm Wax Procurement is Transforming for 2026',
    type: 'Applications and Buyers',
    image: 'https://cdn.chemtradeasia.com/images/market-insight/packaging.webp',
    date: '2026-02-11',
    excerpt: 'How eco-friendly packaging is reshaping the chemical supply chain and reducing carbon footprints.',
    isTop: false,
    isFeatured: true,
    author: 'Tradeasia Research',
    readingTime: '7 min read',
    tags: ['Green Chemistry', 'Palm Wax', 'Procurement'],
    clickCount: 1200
  },
  {
    id: 6,
    slug: 'digitalization-chemical-trade',
    title: `Powering Asia's Factories: The Versatile Role of Soda Ash Dense`,
    type: 'Applications and Buyers',
    image: 'https://cdn.chemtradeasia.com/images/blog/1775559883_OquGca4u.webp',
    date: '2024-04-05',
    excerpt: `Explore the vital applications of Soda Ash Dense in glass, detergents, and chemicals. Learn about its role in Asia's manufacturing boom.`,
    isTop: false,
    isFeatured: false,
    author: 'Tradeasia Research',
    readingTime: '9 min read',
    tags: ['Soda Ash Dense', 'Sodium Carbonate', 'Manufacturing Asia'],
    clickCount: 5400
  },
  {
    id: 7,
    slug: 'the-essential-role-of-soda-ash-dense',
    title: 'The Essential Role of Soda Ash Dense in Glass and Detergents',
    type: 'Applications and Buyers',
    image: 'https://cdn.chemtradeasia.com/images/blog/1775561507_CQDmEpOa.webp',
    date: '2024-03-28',
    excerpt: 'Explore the critical role of Soda Ash Dense in glass and detergent manufacturing in Asia. Learn about applications and sourcing from Tradeasia.',
    isTop: false,
    isFeatured: false,
    author: 'Tradeasia Research',
    readingTime: '6 min read',
    tags: ['Soda Ash Dense', 'Glass Manufacturing', 'Detergents'],
    clickCount: 4100
  },
  {
    id: 8,
    slug: 'soda-ash-dense-a-vital-industrial-chemical-in-asia',
    title: 'Soda Ash Dense: A Vital Industrial Chemical in Asia',
    type: 'Applications and Buyers',
    image: 'https://cdn.chemtradeasia.com/images/blog/1775559549_2favkOyN.webp',
    date: '2024-03-20',
    excerpt: `Explore the properties, key uses, and major industrial applications of Soda Ash Dense in Asia's glass, detergent, and chemical sectors.`,
    isTop: false,
    isFeatured: false,
    author: 'Tradeasia Research',
    readingTime: '5 min read',
    tags: ['Soda Ash Dense', 'Industrial Chemicals', 'Asia Market'],
    clickCount: 3800
  }
];

export const INSIGHT_CATEGORIES = [
  'Insight',
  'Trends and Forecasts',
  'Supply Chain',
  'Regulatory and Compliance',
  'Pricing Indices',
  'Applications and Buyers'
];
